version: '3.5'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - k-network
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - k-network
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - k-network
  example-server-1:
    build: ./example-server/
    environment:
      - spring.cloud.zookeeper.connect-string=zoo1:2181,zoo2:2181,zoo3:2181
      - spring.cloud.zookeeper.discovery.metadata.zone=Zone1
      - kp.instance=zone1.instance1
    networks:
      - k-network
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  example-server-2:
    build: ./example-server/
    environment:
      - spring.cloud.zookeeper.connect-string=zoo1:2181,zoo2:2181,zoo3:2181
      - spring.cloud.zookeeper.discovery.metadata.zone=Zone1
      - kp.instance=zone1.instance2
    networks:
      - k-network
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  example-server-3:
    build: ./example-server/
    environment:
      - spring.cloud.zookeeper.connect-string=zoo1:2181,zoo2:2181,zoo3:2181
      - spring.cloud.zookeeper.discovery.metadata.zone=Zone2
      - kp.instance=zone2.instance1
    networks:
      - k-network
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  example-proxy:
    build: ./example-proxy/
    ports:
      - 8086:8080
    environment:
      - spring.cloud.zookeeper.connect-string=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - k-network
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - example-server-1     
networks: 
  k-network: